# Generated by Django 3.0.9 on 2020-08-13 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteNumber', models.CharField(max_length=10, unique=True)),
                ('customers', models.CharField(max_length=50)),
                ('receiveDay', models.DateField()),
                ('note', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.CharField(max_length=60)),
                ('quantity', models.IntegerField()),
                ('itemGroup', models.CharField(choices=[('TIDAU24', 'TI dầu 24kV'), ('TUDAU24', 'TU dầu 24kV'), ('TIKHO24I', 'TI khô 24kV trong nhà'), ('TIKHO24O', 'TI khô 24kV ngoài trời'), ('TIHT', 'TI hạ thế')], max_length=10)),
                ('status', models.CharField(blank=True, max_length=128)),
                ('check', models.CharField(blank=True, max_length=128)),
                ('conclude', models.CharField(blank=True, max_length=128)),
                ('deadline', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('done', models.BooleanField(choices=[(True, 'Xong'), (False, 'Chưa xong')], default=False)),
                ('noteNumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='warranty.Note')),
            ],
        ),
    ]
