# Generated by Django 3.1 on 2020-08-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='note',
            name='noteNumber',
            field=models.CharField(error_messages={'unique': 'Số phiếu này đã có'}, max_length=10, unique=True),
        ),
    ]
