# Generated by Django 3.1 on 2020-08-18 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0002_auto_20200816_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='check',
            field=models.CharField(blank=True, max_length=128, verbose_name='Đánh giá'),
        ),
        migrations.AlterField(
            model_name='item',
            name='conclude',
            field=models.CharField(blank=True, max_length=128, verbose_name='Kết luận'),
        ),
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(verbose_name='Deadline'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemGroup',
            field=models.CharField(choices=[('TIDAU24', 'TI dầu 24kV'), ('TUDAU24', 'TU dầu 24kV'), ('TIKHO24I', 'TI khô 24kV trong nhà'), ('TIKHO24O', 'TI khô 24kV ngoài trời'), ('TIHT', 'TI hạ thế')], max_length=10, verbose_name='Nhóm sản phẩm'),
        ),
        migrations.AlterField(
            model_name='item',
            name='itemName',
            field=models.CharField(max_length=60, verbose_name='Tên sản phẩm'),
        ),
        migrations.AlterField(
            model_name='item',
            name='noteNumber',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='warranty.note', verbose_name='Phiếu tiếp nhận'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(verbose_name='Số lượng'),
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(blank=True, max_length=128, verbose_name='Tình trạng tiếp nhận'),
        ),
        migrations.AlterField(
            model_name='note',
            name='customers',
            field=models.CharField(max_length=50, verbose_name='Khách hàng'),
        ),
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='note',
            name='noteNumber',
            field=models.CharField(error_messages={'unique': 'Số phiếu này đã có'}, max_length=10, unique=True, verbose_name='Số phiếu'),
        ),
        migrations.AlterField(
            model_name='note',
            name='receiveDay',
            field=models.DateField(verbose_name='Ngày tiếp nhận'),
        ),
        migrations.CreateModel(
            name='ItemLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Nội dung')),
                ('date', models.DateField(verbose_name='Ngày thực hiện')),
                ('note', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='warranty.item', verbose_name='Sản phẩm')),
            ],
        ),
    ]
