# Generated by Django 3.1 on 2020-08-26 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0003_auto_20200818_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dayExport',
            field=models.DateField(null=True, verbose_name='Ngày xuất'),
        ),
        migrations.AddField(
            model_name='item',
            name='numExport',
            field=models.IntegerField(null=True, verbose_name='Số phiếu xuất'),
        ),
        migrations.AddField(
            model_name='note',
            name='customersObj',
            field=models.CharField(choices=[('DAILY', 'Đại lý'), ('NPC', 'NPC'), ('SPC', 'SPC')], max_length=50, null=True, verbose_name='Nhóm khách hàng'),
        ),
        migrations.AddField(
            model_name='note',
            name='numOrder',
            field=models.IntegerField(null=True, verbose_name='Thứ tự'),
        ),
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='done',
            field=models.BooleanField(choices=[(True, 'Đã xong'), (False, 'Chưa xong')], default=False, verbose_name='Xong/ Chưa xong:'),
        ),
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Số lượng'),
        ),
    ]
