# Generated by Django 3.1 on 2020-08-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranty', '0004_auto_20200826_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='dayExport',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày xuất'),
        ),
        migrations.AlterField(
            model_name='item',
            name='note',
            field=models.TextField(blank=True, verbose_name='Ghi chú'),
        ),
        migrations.AlterField(
            model_name='item',
            name='numExport',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số phiếu xuất'),
        ),
    ]
